version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ai_bot_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ai_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media

volumes:
  postgres_data:
